name: Deploy backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: backend

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use defined node version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Read dependencies cache
        uses: actions/cache@v1
        env:
          cache-name: node-modules-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: deploy
        run: npx serverless deploy
